### ISSUE TITLE
Adding to docs

### ISSUE THREAD

**Issue by toshvelaga** [richytong/arche#3]
Is there a way we can add an example in the docs of passing a function as a prop?

For example in a child component how would we pass a function in an onChange event to the parent component?

**Comment by richytong** [comment]
Could you give me a code example of what you are working with right now?

**Comment by richytong** [comment]
Typically you don't pass props from child to parent, instead you want to move the state into the parent component. There's a little bit of a dated article from Dan Abramov that starts everyone in this direction. Worth the read imo

https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0

**Comment by toshvelaga** [comment]
```javascript
const ComponentA = ReactElement((props) => {
  const { onChangeHandler } = props

  return Div([
    {
      id: 'Component-A',
    },
    Input({
      placeholder: 'Enter Your Phone Number',
      value: phoneNumber,
      onChange(e) {
        onChangeHandler(e.target.value)
      },
    }),
  ])
})

export default ComponentA

const ComponentB = ReactElement((props) => {

  return Div([
    {
      id: 'Component-B',
    },
    ComponentA({onChangeHandler: console.log('hello')})
  ])
})

export default ComponentB
```
In this example every time onChange is triggered I want to console.log('hello). How would I do this correctly?

**Comment by richytong** [comment]
So you're on the right track all you need is to make the handler a function in ComponentB (the parent component)

```javascript
const ComponentB = ReactElement((props) => {
  return Div([
    {
      id: 'Component-B',
    },
    ComponentA({onChangeHandler: () => console.log('hello')})
  ])
})
```

**Comment by toshvelaga** [comment]
This works perfectly! Thanks!
